const data = [
  {
    image: "57.PNG",
    title: "order pizza",
    keyword: "reactjs e-commerce",
    demo: "https://fast-pizza-reactjs.netlify.app/",
    code: "https://github.com/codeWithSubhan/fast-pizza-app",
  },

  {
    image: "48.PNG",
    title: "mapty app",
    keyword: "javascript  e-commerce",
    demo: "https://opps-mapty-app-js.netlify.app/",
    code: "https://github.com/codeWithSubhan/opps-mapty-app-js",
  },
  {
    image: "44.PNG",
    title: "bankist app",
    keyword: "javascript  e-commerce",
    demo: "https://array-bankist-app-js.netlify.app/",
    code: "https://github.com/codeWithSubhan/array-bankist-js",
  },
  {
    image: "36.PNG",
    title: "movie app",
    keyword: "reactjs  e-commerce",
    demo: "https://movie-app-reactjss.netlify.app/",
    code: "https://github.com/codeWithSubhan/movie-app-reactjs",
  },
  {
    image: "29.PNG",
    title: "split bill",
    keyword: "reactjs",
    demo: "https://split-bill-reactjs.netlify.app/",
    code: "https://github.com/codeWithSubhan/split-bill-app-reactjs",
  },
  {
    image: "34.PNG",
    title: "weather app",
    keyword: "reactjs",
    demo: "https://classy-weather-reactjs.netlify.app/",
    code: "https://github.com/codeWithSubhan/weather-app-reactjs",
  },
  {
    image: "47.PNG",
    title: "bankist app",
    keyword: "javascript e-commerce",
    demo: "https://advance-dom-website-js.netlify.app/",
    code: "https://github.com/codeWithSubhan/advance-dom-bankist-js",
  },
  {
    image: "25.PNG",
    title: "travel app",
    keyword: "reactjs",
    demo: "https://travel-apps-reactjs.netlify.app/",
    code: "https://github.com/codeWithSubhan/travel-app-reactjs",
  },
  {
    image: "37.PNG",
    title: "atomic blog",
    keyword: "reactjs",
    demo: "https://atomic-blog-app-reactjs.netlify.app/",
    code: "https://github.com/codeWithSubhan/atomic-blog-app-reactjs",
  },
  {
    image: "41.PNG",
    title: "guess number",
    keyword: "javascript games",
    demo: "https://guess-my-numbr-js.netlify.app/",
    code: "https://github.com/codeWithSubhan/guess-my-number-js",
  },
  {
    image: "32.PNG",
    title: "react quiz",
    keyword: "reacjs games",
    demo: "https://react-quiz-app-reactjs.netlify.app/",
    code: "https://github.com/codeWithSubhan/react-quiz-app-reactjs",
  },
  {
    image: "43.PNG",
    title: "pig game",
    keyword: "javascript games",
    demo: "https://pig-gme-js.netlify.app/",
    code: "https://github.com/codeWithSubhan/pig-game-js",
  },
  {
    image: "26.PNG",
    title: "pizza app",
    keyword: "reactjs",
    demo: "https://pizza-apps-reactjs.netlify.app/",
    code: "https://github.com/codeWithSubhan/pizza-app-reacjs",
  },
  {
    image: "58.PNG",
    title: "behind the scene",
    keyword: "reactjs",
    demo: "https://behind-the-scene-reactjs.netlify.app/",
    code: "https://github.com/codeWithSubhan/behind-the-scene-reactjs",
  },
  {
    image: "38.PNG",
    title: "e-commerce",
    keyword: "javascript",
    demo: "https://e-commrce-js.netlify.app/",
    code: "https://github.com/codeWithSubhan/E-commerce.github.io",
  },
  {
    image: "16.PNG",
    title: "snake game",
    keyword: "javascript games",
    demo: "https://snke-game.netlify.app/",
    code: "https://github.com/codeWithSubhan/snakeGame",
  },

  {
    image: "2.PNG",
    title: "Analog Clock",
    keyword: "javascript",
    demo: "https://analogcolck.netlify.app/",
    code: "https://github.com/codeWithSubhan/analogClock.github.io",
  },
  {
    image: "7.PNG",
    title: "cup of tea",
    keyword: "html/css",
    demo: "https://tea-of-cup.netlify.app/",
    code: "https://github.com/codeWithSubhan/cup_of_tea",
  },
  {
    image: "46.PNG",
    title: "asynchronous code",
    keyword: "javascript",
    demo: "https://gregarious-chebakia-6bc078.netlify.app/",
    code: "https://github.com/codeWithSubhan/asynchronous-code-js",
  },
  {
    image: "0.PNG",
    title: "music player",
    keyword: "javascript",
    demo: "https://music-palyer.netlify.app/",
    code: "https://github.com/codeWithSubhan/song.github.io",
  },
  {
    image: "1.PNG",
    title: "typing test",
    keyword: "javascript",
    demo: "https://typng-test.netlify.app/",
    code: "https://github.com/codeWithSubhan/typingTest.github.io",
  },
  {
    image: "14.PNG",
    title: "emoji eyes",
    keyword: "javascript",
    demo: "https://emoji-eyes.netlify.app/",
    code: "https://github.com/codeWithSubhan/emoji_eyes",
  },

  {
    image: "18.PNG",
    title: "doraemon puzzles",
    keyword: "javascript games",
    demo: "https://doraemon-puzzle.netlify.app/",
    code: "https://github.com/codeWithSubhan/Doraemon-puzzles",
  },
  {
    image: "20.PNG",
    title: "bank app",
    keyword: "reactjs",
    demo: "https://bank-app-redux.netlify.app/",
    code: "https://github.com/codeWithSubhan/Bank-App-Redux",
  },

  {
    image: "45.PNG",
    title: "bankist app",
    keyword: "javascript",
    demo: "https://array-bankist-number-data-app-js.netlify.app/",
    code: "https://github.com/codeWithSubhan/bankist-number-date-timer-js",
  },
  {
    image: "27.PNG",
    title: "accordion",
    keyword: "reactjs",
    demo: "https://accorddion-reactjs.netlify.app/",
    code: "https://github.com/codeWithSubhan/accordion-reactjs",
  },
  {
    image: "10.PNG",
    title: "film countdown",
    keyword: "html/css",
    demo: "https://film-countdown.netlify.app/",
    code: "https://github.com/codeWithSubhan/film-counDown",
  },
  {
    image: "21.PNG",
    title: "tabs",
    keyword: "reactjs",
    demo: "https://tabs-reacjs.netlify.app/",
    code: "https://github.com/codeWithSubhan/tab-reactjs",
  },
  {
    image: "12.PNG",
    title: "flip card",
    keyword: "html/css",
    demo: "https://flipcard3d.netlify.app/",
    code: "https://github.com/codeWithSubhan/flip-card",
  },
  {
    image: "13.PNG",
    title: "two ring",
    keyword: "html/css",
    demo: "https://ringtwo.netlify.app/",
    code: "https://github.com/codeWithSubhan/two_ring",
  },

  {
    image: "8.PNG",
    title: "icon effect",
    keyword: "html/css",
    demo: "https://icons-effect.netlify.app/",
    code: "https://github.com/codeWithSubhan/Icon_Effect",
  },
  {
    image: "11.PNG",
    title: "car move",
    keyword: "html/css",
    demo: "https://car-move.netlify.app/",
    code: "https://github.com/codeWithSubhan/car-move",
  },
  {
    image: "9.PNG",
    title: "love balls",
    keyword: "javascript",
    demo: "https://loveball.netlify.app/",
    code: "https://github.com/codeWithSubhan/love_ball",
  },
  {
    image: "42.PNG",
    title: "modal",
    keyword: "javascript",
    demo: "https://modal-show-js.netlify.app/",
    code: "https://github.com/codeWithSubhan/modal-js",
  },
  {
    image: "39.PNG",
    title: "form validation",
    keyword: "javascript",
    demo: "https://form-valid-js.netlify.app/",
    code: "https://github.com/codeWithSubhan/ValidForm.github.io",
  },
  {
    image: "22.PNG",
    title: "flesh card",
    keyword: "reactjs",
    demo: "https://flesh-card-reactjs.netlify.app/",
    code: "https://github.com/codeWithSubhan/flesh-card-reactjs",
  },
  {
    image: "24.PNG",
    title: "steps",
    keyword: "reactjs",
    demo: "https://steps-reactjs.netlify.app/",
    code: "https://github.com/codeWithSubhan/steps-reactjs",
  },
  {
    image: "19.PNG",
    title: "valid password",
    keyword: "javascript",
    demo: "https://password-valid.netlify.app/",
    code: "https://github.com/codeWithSubhan/password_validation",
  },
  {
    image: "3.PNG",
    title: "custome button",
    keyword: "html/css",
    demo: "https://custome-button.netlify.app/",
    code: "https://github.com/codeWithSubhan/custome_button",
  },
  {
    image: "6.PNG",
    title: "drop of water",
    keyword: "html/css",
    demo: "https://drop-of-water.netlify.app/",
    code: "https://github.com/codeWithSubhan/drop_of_water",
  },
  {
    image: "15.PNG",
    title: "180 rotate",
    keyword: "html/css",
    demo: "https://180rotate.netlify.app/",
    code: "https://github.com/codeWithSubhan/180_deg_rotate",
  },
  {
    image: "4.PNG",
    title: "3d text",
    keyword: "html/css",
    demo: "https://3d-text-editable.netlify.app/",
    code: "https://github.com/codeWithSubhan/3d-text-aditable",
  },
  {
    image: "5.PNG",
    title: "3d circle",
    keyword: "html/css",
    demo: "https://circle-loader.netlify.app/",
    code: "https://github.com/codeWithSubhan/circle_loader",
  },
  {
    image: "17.PNG",
    title: "distortion effect",
    keyword: "html/css",
    demo: "https://distortion-effects.netlify.app/",
    code: "https://github.com/codeWithSubhan/Distortion_effect",
  },
  {
    image: "40.PNG",
    title: "bulb",
    keyword: "html/css",
    demo: "https://bulb-switchon.netlify.app/",
    code: "https://github.com/codeWithSubhan/BULB",
  },
  {
    image: "53.PNG",
    title: "ludo game",
    keyword: "javascript games",
    demo: "https://ludo-gme-js.netlify.app/",
    code: "https://github.com/codeWithSubhan/Ludo_Game",
  },
  {
    image: "52.PNG",
    title: "lover percentage",
    keyword: "javascript",
    demo: "https://lover-percentage-js.netlify.app/",
    code: "https://github.com/codeWithSubhan/love_percentage",
  },
  {
    image: "31.PNG",
    title: "bank app",
    keyword: "reactjs",
    demo: "https://reducer-bank-app-reactjs.netlify.app/",
    code: "https://github.com/codeWithSubhan/bank-app-useReducer-reactjs",
  },
  {
    image: "23.PNG",
    title: "counter",
    keyword: "reactjs",
    demo: "https://countr-reactjs.netlify.app/",
    code: "https://github.com/codeWithSubhan/counter-reactjs",
  },

  {
    image: "28.PNG",
    title: "tips ",
    keyword: "reactjs",
    demo: "https://tips-reactjs.netlify.app/",
    code: "https://github.com/codeWithSubhan/tips-reactjs",
  },

  {
    image: "30.PNG",
    title: "custome hook",
    keyword: "reactjs",
    demo: "https://geolocation-reactjs.netlify.app/",
    code: "https://github.com/codeWithSubhan/custome-hook-reactjs",
  },

  {
    image: "33.PNG",
    title: "currency convert",
    keyword: "reactjs",
    demo: "https://currency-convert-reactjs.netlify.app/",
    code: "https://github.com/codeWithSubhan/currency-convert-reactjs",
  },

  {
    image: "35.PNG",
    title: "expand text",
    keyword: "reactjs",
    demo: "https://expand-text-reactjs.netlify.app/",
    code: "https://github.com/codeWithSubhan/expand-text-reactjs",
  },

  {
    image: "49.PNG",
    title: "compound component",
    keyword: "reactjs",
    demo: "https://compound-component-reatjs.netlify.app/",
    code: "https://github.com/codeWithSubhan/compound-component-reatjs",
  },
  {
    image: "50.PNG",
    title: "calculator",
    keyword: "javascript",
    demo: "https://calculatr-js.netlify.app/",
    code: "https://github.com/codeWithSubhan/calculator",
  },
  {
    image: "51.PNG",
    title: "bmi",
    keyword: "javascript",
    demo: "https://bmi-jss.netlify.app/",
    code: "https://github.com/codeWithSubhan/bmi",
  },

  {
    image: "54.PNG",
    title: "print page",
    keyword: "javascript",
    demo: "https://print-page-js.netlify.app/",
    code: "https://github.com/codeWithSubhan/print_page",
  },
  {
    image: "55.PNG",
    title: "reverse string",
    keyword: "javascript",
    demo: "https://reverse-str-js.netlify.app/",
    code: "https://github.com/codeWithSubhan/reverse_string",
  },
  {
    image: "56.PNG",
    title: "digital clock",
    keyword: "javascript",
    demo: "https://digital-colck.netlify.app/",
    code: "https://github.com/codeWithSubhan/digital-clock-js",
  },
  {
    image: "59.PNG",
    title: "card",
    keyword: "typescript",
    demo: "https://card-ts.netlify.app/",
    code: "https://github.com/codeWithSubhan/card-ts",
  },
  {
    image: "60.png",
    title: "break out game",
    keyword: "reactjs games",
    demo: "https://breakoutgame-reactjs.netlify.app/",
    code: "https://github.com/codeWithSubhan/Breakout-Game--reactjs",
  },
  {
    image: "61.png",
    title: "figma design",
    keyword: "nextjs typescript",
    demo: "https://nextjs-ts-figma.netlify.app/",
    code: "https://github.com/codeWithSubhan/nextjs-ts-figma",
  },
  {
    image: "62.png",
    title: "curd operation redux-persist",
    keyword: "nextjs typescript",
    demo: "https://curd-operation-nextjs-ts-reduxpersist.netlify.app/",
    code: "https://github.com/codeWithSubhan/curd-operation-nextjs14-redux-persist",
  },
  {
    image: "63.png",
    title: "redio card",
    keyword: "reactjs",
    demo: "https://01-interview-reactjs-figma.netlify.app/",
    code: "https://github.com/codeWithSubhan/01-Interview",
  },
  {
    image: "64.png",
    title: "protect routes",
    keyword: "reactjs",
    demo: "https://protect-routes-reactjs.netlify.app/",
    code: "https://github.com/codeWithSubhan/protect-routes-reactjs",
  },
  {
    image: "65.png",
    title: "device width",
    keyword: "javascript",
    demo: "https://device-with.netlify.app/",
    code: "https://github.com/codeWithSubhan/device-with",
  },
  {
    image: "66.png",
    title: "static website",
    keyword: "html/css",
    demo: "https://device-with.netlify.app/",
    code: "https://github.com/codeWithSubhan/device-with",
  },
  {
    image: "67.png",
    title: "curd operation localstorage",
    keyword: "reactjs",
    demo: "https://crud-localstorage-reactjs.netlify.app/",
    code: "https://github.com/codeWithSubhan/crud-reactjs",
  },
  {
    image: "68.png",
    title: "tic tak toy",
    keyword: "reactjs games",
    demo: "https://reactjs-tic-tac-toy.netlify.app/",
    code: "https://github.com/codeWithSubhan/tic-tac-toe-reactjs",
  },
  {
    image: "69.png",
    title: "todo list",
    keyword: "reactjs",
    demo: "https://to-do-list-reactsj.netlify.app/",
    code: "https://github.com/codeWithSubhan/tic-tac-toe-reactjs",
  },
];

export default data;
