const data = [
  {
    title: 'music player',
    keyword: 'javascript',
    demo: 'https://music-palyer.netlify.app/',
    code: 'https://github.com/codeWithSubhan/song.github.io',
  },
  {
    title: 'typing test',
    keyword: 'javascript',
    demo: 'https://typng-test.netlify.app/',
    code: 'https://github.com/codeWithSubhan/typingTest.github.io',
  },
  {
    title: 'Analog Clock',
    keyword: 'javascript',
    demo: 'https://analogcolck.netlify.app/',
    code: 'https://github.com/codeWithSubhan/analogClock.github.io',
  },
  {
    title: 'custome button',
    keyword: 'html',
    demo: 'https://custome-button.netlify.app/',
    code: 'https://github.com/codeWithSubhan/custome_button',
  },
  {
    title: '3d text editable',
    keyword: 'html',
    demo: 'https://3d-text-editable.netlify.app/',
    code: 'https://github.com/codeWithSubhan/3d-text-aditable',
  },
  {
    title: '3d circle',
    keyword: 'html',
    demo: 'https://circle-loader.netlify.app/',
    code: 'https://github.com/codeWithSubhan/circle_loader',
  },
  {
    title: 'drop of water',
    keyword: 'html',
    demo: 'https://drop-of-water.netlify.app/',
    code: 'https://github.com/codeWithSubhan/drop_of_water',
  },
  {
    title: 'cup of tea',
    keyword: 'html',
    demo: 'https://tea-of-cup.netlify.app/',
    code: 'https://github.com/codeWithSubhan/cup_of_tea',
  },
  {
    title: 'icon effect',
    keyword: 'html',
    demo: 'https://icons-effect.netlify.app/',
    code: 'https://github.com/codeWithSubhan/Icon_Effect',
  },
  {
    title: 'love balls',
    keyword: 'javascript',
    demo: 'https://loveball.netlify.app/',
    code: 'https://github.com/codeWithSubhan/love_ball',
  },
  {
    title: 'film countdown',
    keyword: 'html',
    demo: 'https://film-countdown.netlify.app/',
    code: 'https://github.com/codeWithSubhan/film-counDown',
  },
  {
    title: 'car move game',
    keyword: 'html',
    demo: 'https://car-move.netlify.app/',
    code: 'https://github.com/codeWithSubhan/car-move',
  },
  {
    title: 'flip card',
    keyword: 'html',
    demo: 'https://flipcard3d.netlify.app/',
    code: 'https://github.com/codeWithSubhan/flip-card',
  },
  {
    title: 'two ring',
    keyword: 'html',
    demo: 'https://ringtwo.netlify.app/',
    code: 'https://github.com/codeWithSubhan/two_ring',
  },
  {
    title: 'emoji eyes game',
    keyword: 'javascript',
    demo: 'https://emoji-eyes.netlify.app/',
    code: 'https://github.com/codeWithSubhan/emoji_eyes',
  },
  {
    title: '180 rotate',
    keyword: 'html',
    demo: 'https://180rotate.netlify.app/',
    code: 'https://github.com/codeWithSubhan/180_deg_rotate',
  },
  {
    title: 'snake game',
    keyword: 'javascript',
    demo: 'https://snke-game.netlify.app/',
    code: 'https://github.com/codeWithSubhan/snakeGame',
  },
  {
    title: 'distortion effect',
    keyword: 'html',
    demo: 'https://distortion-effects.netlify.app/',
    code: 'https://github.com/codeWithSubhan/Distortion_effect',
  },
  {
    title: 'doraemon puzzles',
    keyword: 'html',
    demo: 'https://doraemon-puzzle.netlify.app/',
    code: 'https://github.com/codeWithSubhan/Doraemon-puzzles',
  },
  {
    title: 'valid password',
    keyword: 'javascript',
    demo: 'https://password-valid.netlify.app/',
    code: 'https://github.com/codeWithSubhan/password_validation',
  },
  {
    title: 'bank app',
    keyword: 'reactjs',
    demo: 'https://bank-app-redux.netlify.app/',
    code: 'https://github.com/codeWithSubhan/Bank-App-Redux',
  },
  {
    title: 'tabs',
    keyword: 'reactjs',
    demo: 'https://tabs-reacjs.netlify.app/',
    code: 'https://github.com/codeWithSubhan/tab-reactjs',
  },
  {
    title: 'flesh card',
    keyword: 'reactjs',
    demo: 'https://flesh-card-reactjs.netlify.app/',
    code: 'https://github.com/codeWithSubhan/flesh-card-reactjs',
  },
  {
    title: 'counter',
    keyword: 'reactjs',
    demo: 'https://countr-reactjs.netlify.app/',
    code: 'https://github.com/codeWithSubhan/counter-reactjs',
  },
  {
    title: 'steps',
    keyword: 'reactjs',
    demo: 'https://steps-reactjs.netlify.app/',
    code: 'https://github.com/codeWithSubhan/steps-reactjs',
  },
  {
    title: 'travel app',
    keyword: 'reactjs',
    demo: 'https://travel-apps-reactjs.netlify.app/',
    code: 'https://github.com/codeWithSubhan/travel-app-reactjs',
  },
  {
    title: 'pizza app',
    keyword: 'reactjs',
    demo: 'https://pizza-apps-reactjs.netlify.app/',
    code: 'https://github.com/codeWithSubhan/pizza-app-reacjs',
  },
  {
    title: 'accordion',
    keyword: 'reactjs',
    demo: 'https://accorddion-reactjs.netlify.app/',
    code: 'https://github.com/codeWithSubhan/accordion-reactjs',
  },
  {
    title: 'tips app',
    keyword: 'reactjs',
    demo: 'https://tips-reactjs.netlify.app/',
    code: 'https://github.com/codeWithSubhan/tips-reactjs',
  },
  {
    title: 'split bill app',
    keyword: 'reactjs',
    demo: 'https://split-bill-reactjs.netlify.app/',
    code: 'https://github.com/codeWithSubhan/split-bill-app-reactjs',
  },
  {
    title: 'custome hook',
    keyword: 'reactjs',
    demo: 'https://geolocation-reactjs.netlify.app/',
    code: 'https://github.com/codeWithSubhan/custome-hook-reactjs',
  },
  {
    title: 'bank app',
    keyword: 'reactjs',
    demo: 'https://reducer-bank-app-reactjs.netlify.app/',
    code: 'https://github.com/codeWithSubhan/bank-app-useReducer-reactjs',
  },
  {
    title: 'react quiz',
    keyword: 'reacjs',
    demo: 'https://react-quiz-app-reactjs.netlify.app/',
    code: 'https://github.com/codeWithSubhan/react-quiz-app-reactjs',
  },
  {
    title: 'currency convert',
    keyword: 'reactjs',
    demo: 'https://currency-convert-reactjs.netlify.app/',
    code: 'https://github.com/codeWithSubhan/currency-convert-reactjs',
  },
  {
    title: 'weather app',
    keyword: 'reactjs',
    demo: 'https://classy-weather-reactjs.netlify.app/',
    code: 'https://github.com/codeWithSubhan/weather-app-reactjs',
  },
  {
    title: 'expand text',
    keyword: 'reactjs',
    demo: 'https://expand-text-reactjs.netlify.app/',
    code: 'https://github.com/codeWithSubhan/expand-text-reactjs',
  },
  {
    title: 'movie app',
    keyword: 'reactjs',
    demo: 'https://movie-app-reactjss.netlify.app/',
    code: 'https://github.com/codeWithSubhan/movie-app-reactjs',
  },
  {
    title: 'atomic blog',
    keyword: 'reactjs',
    demo: 'https://atomic-blog-app-reactjs.netlify.app/',
    code: 'https://github.com/codeWithSubhan/atomic-blog-app-reactjs',
  },
  {
    title: 'e-commerce',
    keyword: 'js',
    demo: 'https://e-commrce-js.netlify.app/',
    code: 'https://github.com/codeWithSubhan/E-commerce.github.io',
  },
  {
    title: 'form validation',
    keyword: 'js',
    demo: 'https://form-valid-js.netlify.app/',
    code: 'https://github.com/codeWithSubhan/ValidForm.github.io',
  },
  {
    title: 'bulb',
    keyword: 'html',
    demo: 'https://bulb-switchon.netlify.app/',
    code: 'https://github.com/codeWithSubhan/BULB',
  },
  {
    title: 'guess number',
    keyword: 'js',
    demo: 'https://guess-my-numbr-js.netlify.app/',
    code: 'https://github.com/codeWithSubhan/guess-my-number-js',
  },
  {
    title: 'modal',
    keyword: 'js',
    demo: 'https://modal-show-js.netlify.app/',
    code: 'https://github.com/codeWithSubhan/modal-js',
  },
  {
    title: 'pig game',
    keyword: 'js',
    demo: 'https://pig-gme-js.netlify.app/',
    code: 'https://github.com/codeWithSubhan/pig-game-js',
  },
  {
    title: 'bankist app',
    keyword: 'js',
    demo: 'https://array-bankist-app-js.netlify.app/',
    code: 'https://github.com/codeWithSubhan/array-bankist-js',
  },
  {
    title: 'bankist app',
    keyword: 'js',
    demo: 'https://array-bankist-number-data-app-js.netlify.app/',
    code: 'https://github.com/codeWithSubhan/bankist-number-date-timer-js',
  },
  {
    title: 'asynchronous code',
    keyword: 'js',
    demo: 'https://gregarious-chebakia-6bc078.netlify.app/',
    code: 'https://github.com/codeWithSubhan/asynchronous-code-js',
  },
  {
    title: 'bankist app',
    keyword: 'https://advance-dom-website-js.netlify.app/',
    demo: 'js',
    code: 'https://github.com/codeWithSubhan/advance-dom-bankist-js',
  },
  {
    title: 'mapty app',
    keyword: 'js',
    demo: 'https://opps-mapty-app-js.netlify.app/',
    code: 'https://github.com/codeWithSubhan/opps-mapty-app-js',
  },
  {
    title: 'compound component',
    keyword: 'reactjs',
    demo: 'https://compound-component-reatjs.netlify.app/',
    code: 'https://github.com/codeWithSubhan/compound-component-reatjs',
  },
  {
    title: 'calculator',
    keyword: 'js',
    demo: 'https://calculatr-js.netlify.app/',
    code: 'https://github.com/codeWithSubhan/calculator',
  },
  {
    title: 'bmi',
    keyword: 'js',
    demo: 'https://bmi-jss.netlify.app/',
    code: 'https://github.com/codeWithSubhan/bmi',
  },
  {
    title: 'lover percentage',
    keyword: 'js',
    demo: 'https://lover-percentage-js.netlify.app/',
    code: 'https://github.com/codeWithSubhan/love_percentage',
  },
  {
    title: 'lodo game',
    keyword: 'js',
    demo: 'https://ludo-gme-js.netlify.app/',
    code: 'https://github.com/codeWithSubhan/Ludo_Game',
  },
  {
    title: 'print page',
    keyword: 'js',
    demo: 'https://print-page-js.netlify.app/',
    code: 'https://github.com/codeWithSubhan/print_page',
  },
  {
    title: 'reverse string',
    keyword: 'js',
    demo: 'https://reverse-str-js.netlify.app/',
    code: 'https://github.com/codeWithSubhan/reverse_string',
  },
  {
    title: 'digital clock',
    keyword: 'js',
    demo: 'https://digital-colck.netlify.app/',
    code: 'https://github.com/codeWithSubhan/digital-clock-js',
  },
];

export default data;
